/**
 * หุ้นไทย — SET / ก.ล.ต.
 *
 * ต่างจาก US/HK ตรงที่ไม่มี XBRL API สาธารณะแบบ SEC EDGAR
 * กลยุทธ์ 3 ชั้น:
 *   1. Yahoo (.BK)        -> ratios, ราคา, งบย่อ  [ฟรี ไม่ต้องสมัคร]
 *   2. ก.ล.ต. SEC API     -> งบการเงิน structured  [ฟรี ต้องสมัคร key]
 *   3. SET website        -> fallback / verify     [scrape]
 *
 * สมัคร API key: https://api-portal.sec.or.th
 *
 * Real endpoints (confirmed against a live key, replacing the guessed /FinancialReport/... path):
 *   1. /v1/one-report/sbo/{report_year}/info/{T|E}                — company directory,
 *      symbol -> unique_id (e.g. 'PTT' -> 'C0000001074'). Returns the FULL list in one call.
 *   2. /v1/one-report/fs/{report_year}/financial_statement/{unique_id} — the actual financials,
 *      keyed by unique_id (not symbol). Line items are keyed by a numeric `set_code`
 *      (e.g. '410100'), not a field name — there is no published set_code dictionary anywhere.
 *
 * TH_SET_CODE_MAP below is deliberately near-empty: see docs/th-set-code-map.md, generated by
 * scripts/build-th-set-code-map.ts, which cross-references set_codes against Yahoo's own
 * same-year historical figures for the same ticker. A code only gets mapped once it's CONFIRMED
 * there (independently matched for >=2 different companies) — LIKELY/UNKNOWN codes are real
 * candidates (e.g. revenue=410100 and netIncome=460100 both matched GULF's 2021 figures at
 * exactly 1.00x) but stay out of FinancialFact until a second company confirms them, since a
 * single coincidental match isn't enough evidence for a number that gets written into the
 * ledger as fact. Real coverage gap found while building that map: most large-cap tickers
 * (CPALL, ADVANC, AOT, HMPRO, CRC, BJC, CPN, TRUE tried) have NO financial_statement data via
 * this API at all — only a handful of companies (PTT, KTB, GULF confirmed) do.
 */

import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

const SEC_TH_BASE = 'https://api.sec.or.th';
const KEY = process.env.SEC_TH_API_KEY ?? '';

function thHeaders() {
  if (!KEY) throw new Error('ไม่มี SEC_TH_API_KEY — สมัครฟรีที่ https://api-portal.sec.or.th');
  return { 'Ocp-Apim-Subscription-Key': KEY, Accept: 'application/json' };
}

// ---------- symbol -> unique_id ----------

let uniqueIdCache: Map<string, string> | null = null;

/** the company directory is a single ~500KB call covering all listed companies for one report_year */
async function loadUniqueIdDirectory(): Promise<Map<string, string>> {
  if (uniqueIdCache) return uniqueIdCache;
  for (const year of [2023, 2022, 2021]) {
    const res = await fetch(`${SEC_TH_BASE}/v1/one-report/sbo/${year}/info/E`, { headers: thHeaders() });
    if (res.status !== 200) continue;
    const data = (await res.json()) as { symbol: string; unique_id: string }[];
    uniqueIdCache = new Map(data.map((c) => [c.symbol.toUpperCase(), c.unique_id]));
    return uniqueIdCache;
  }
  throw new Error('ดึงรายชื่อบริษัทจาก ก.ล.ต. ไม่ได้ทุกปีที่ลอง (2021-2023)');
}

export async function getUniqueId(symbol: string): Promise<string | null> {
  const dir = await loadUniqueIdDirectory();
  return dir.get(symbol.toUpperCase()) ?? null;
}

// ---------- normalize ticker ----------

/** 'PTT' | 'PTT.BK' | 'SET:PTT'  ->  { symbol: 'PTT', yahoo: 'PTT.BK' } */
export function normalizeThai(input: string) {
  const symbol = input
    .replace(/\.BK$/i, '')
    .replace(/^SET:/i, '')
    .trim()
    .toUpperCase();
  return { symbol, yahoo: `${symbol}.BK` };
}

export function isThai(ticker: string): boolean {
  return /\.BK$/i.test(ticker) || /^SET:/i.test(ticker);
}

// ---------- ก.ล.ต. — งบการเงิน ----------

export interface ThFinancialRow {
  metricName: string;
  value: number;
  unit: string;
  period: string;        // '2021-12-31' — calendar year end, derived from which asof_* column
  quarter: string;       // always 'FY' — this endpoint only returns annual figures
  statementType: 'BS' | 'IS' | 'CF';
}

interface ThRawRow {
  report_year: string;
  unique_id: string;
  account_form: string;
  financial_statement: string; // 'balanceSheet' | 'incomeStatement' | 'cashFlow' | 'financialRatio'
  unit: number; // e.g. 1000 — multiply before use
  set_code: string;
  sequence: number;
  asof_year: number;
  asof_yesteryear: number;
  asof_year_before_yesteryear: number;
}

/** one report_year call — each call itself carries a 3-year comparison (asof_year/yesteryear/prior2) */
export async function fetchThFinancials(uniqueId: string, reportYear: number): Promise<ThRawRow[] | null> {
  const url = `${SEC_TH_BASE}/v1/one-report/fs/${reportYear}/financial_statement/${uniqueId}`;
  const res = await fetch(url, { headers: thHeaders() });
  if (res.status === 204 || res.status === 404) return null; // ปีนั้นไม่มีข้อมูล
  if (!res.ok) throw new Error(`SEC TH ${res.status} — ${uniqueId} report_year=${reportYear}`);
  return res.json();
}

/** ดึงย้อนหลัง N ปี — สำหรับ Gate 0. คืน raw rows ทุก report_year ที่มีข้อมูลจริง */
export async function fetchThHistory(symbol: string, years = 6): Promise<{ reportYear: number; rows: ThRawRow[] }[]> {
  const uniqueId = await getUniqueId(symbol);
  if (!uniqueId) return [];

  const now = new Date().getFullYear();
  const out: { reportYear: number; rows: ThRawRow[] }[] = [];
  for (let y = now; y > now - years; y--) {
    const rows = await fetchThFinancials(uniqueId, y);
    if (rows) out.push({ reportYear: y, rows });
    await sleep(150); // เกรงใจ rate limit (portal quotes 3000 req / 300s)
  }
  return out;
}

/**
 * set_code -> metricName, CONFIRMED tier only (docs/th-set-code-map.md). Deliberately empty right
 * now — see the module doc comment above for why LIKELY candidates (410100=Revenue,
 * 460100=NetIncome, matched at 1.00x for GULF 2021) aren't included yet.
 */
export const TH_SET_CODE_MAP: Record<string, { metricName: string; unit: string }> = {};

export function flattenThFacts(rows: ThRawRow[]): ThFinancialRow[] {
  const statementType: Record<string, ThFinancialRow['statementType']> = {
    balanceSheet: 'BS',
    incomeStatement: 'IS',
    cashFlow: 'CF',
  };

  const out: ThFinancialRow[] = [];
  for (const r of rows) {
    const def = TH_SET_CODE_MAP[r.set_code];
    const type = statementType[r.financial_statement];
    if (!def || !type) continue;

    const reportYear = Number(r.report_year);
    const unit = Number(r.unit) || 1;
    for (const [yearOffset, column] of [
      [0, 'asof_year'],
      [1, 'asof_yesteryear'],
      [2, 'asof_year_before_yesteryear'],
    ] as const) {
      const raw = r[column];
      if (raw == null) continue;
      out.push({
        metricName: def.metricName,
        value: raw * unit,
        unit: def.unit,
        period: `${reportYear - yearOffset}-12-31`,
        quarter: 'FY',
        statementType: type,
      });
    }
  }
  return out;
}

// ---------- SET — ข้อมูลบริษัท / ราคา ----------

/**
 * SET ไม่มี public API อย่างเป็นทางการ
 * endpoint นี้เป็นตัวที่หน้าเว็บ set.or.th เรียกเอง — อาจเปลี่ยนได้ทุกเมื่อ
 * ถ้าพัง -> fallback Yahoo (.BK) อย่างเดียว
 */
export async function fetchSetProfile(symbol: string) {
  const url = `https://www.set.or.th/api/set/stock/${symbol}/profile?lang=en`;
  const res = await fetch(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      Referer: `https://www.set.or.th/en/market/product/stock/quote/${symbol}/price`,
      Accept: 'application/json',
    },
  });
  if (!res.ok) return null;
  return res.json();
}

export async function fetchSetHighlight(symbol: string) {
  const url = `https://www.set.or.th/api/set/factsheet/${symbol}/financialdata?lang=en`;
  const res = await fetch(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      Referer: `https://www.set.or.th/en/market/product/stock/quote/${symbol}/factsheet`,
      Accept: 'application/json',
    },
  });
  if (!res.ok) return null;
  return res.json();
}

// ---------- archive -> RawSource ----------

async function archiveJson(
  ticker: string,
  market: string,
  filename: string,
  payload: unknown,
  rootDir: string
) {
  const body = JSON.stringify(payload, null, 2);
  const hash = crypto.createHash('sha256').update(body).digest('hex');
  const day = new Date().toISOString().slice(0, 10);
  const dir = path.join(rootDir, market, ticker, day);
  await fs.mkdir(dir, { recursive: true });
  const filePath = path.join(dir, filename);
  await fs.writeFile(filePath, body);
  return { filePath, sha256Hash: hash };
}

export async function archiveThai(input: string, rootDir = 'raw-sources') {
  const { symbol } = normalizeThai(input);
  const rawSources: any[] = [];
  const facts: ThFinancialRow[] = [];
  const warnings: string[] = [];

  // 1. ก.ล.ต. — งบ structured (ถ้ามี key)
  let yearsAvailable = 0;
  if (KEY) {
    try {
      const history = await fetchThHistory(symbol);
      if (history.length) {
        // each report_year call carries a 3-year comparison (asof_year/yesteryear/prior2) —
        // Gate 0 counts real distinct calendar years covered, not just successful calls
        const calendarYears = new Set<number>();
        for (const h of history) {
          for (const r of h.rows) {
            const y = Number(r.report_year);
            if (r.asof_year != null) calendarYears.add(y);
            if (r.asof_yesteryear != null) calendarYears.add(y - 1);
            if (r.asof_year_before_yesteryear != null) calendarYears.add(y - 2);
          }
        }
        yearsAvailable = calendarYears.size;

        const a = await archiveJson(symbol, 'TH_SEC', 'financials.json', history, rootDir);
        rawSources.push({
          ticker: symbol, market: 'TH_SEC', ...a,
          fetchedBy: 'th.ts:fetchThHistory', fetchedAt: new Date(),
        });
        for (const h of history) facts.push(...flattenThFacts(h.rows));
      }
    } catch (e) {
      warnings.push(`ก.ล.ต. ล้มเหลว: ${(e as Error).message}`);
    }
  } else {
    warnings.push('ไม่มี SEC_TH_API_KEY — ข้ามงบจาก ก.ล.ต. ใช้ Yahoo อย่างเดียว');
  }

  // 2. SET factsheet (best effort)
  try {
    const [profile, highlight] = await Promise.all([
      fetchSetProfile(symbol),
      fetchSetHighlight(symbol),
    ]);
    if (profile || highlight) {
      const a = await archiveJson(symbol, 'SET', 'factsheet.json', { profile, highlight }, rootDir);
      rawSources.push({
        ticker: symbol, market: 'SET', ...a,
        fetchedBy: 'th.ts:fetchSet', fetchedAt: new Date(),
      });
    }
  } catch (e) {
    warnings.push(`SET ล้มเหลว: ${(e as Error).message}`);
  }

  return {
    symbol,
    yahooTicker: `${symbol}.BK`,
    rawSources,
    facts,
    warnings,
    gate0: { source: 'TH', years: yearsAvailable, passed: yearsAvailable >= 3 },
  };
}

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
